languages:
   JavaScript: true
exclude_paths:
 - "test/**/*"
 - "docs/**/*"
 - "README.md"
 - "CHANGELOG.md"
 - "package.json"
 - "dist/*.*"
 - "lib/*.*"
 - "bower.json"
 - "webpack.config.js"
 - "karma.config.js"